#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent passwd solr > /dev/null; then
      # user needs a login shell because solr's init script uses `su -` for the user switch
      adduser --system --group --home /var/lib/solr --shell /bin/sh --quiet solr
    fi

    if [ ! -e "/var/lib/solr/solr.xml" ] ; then
      cp /opt/solr/server/solr/solr.xml /var/lib/solr/solr.xml
    fi

    chown -R solr:solr /var/log/solr /var/lib/solr /var/run/solr

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
