#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent passwd statsd > /dev/null; then
      adduser --system --group --no-create-home --quiet statsd
    fi

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
