FROM ubuntu:trusty

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get -y install \
    curl wget build-essential ruby ruby-dev unzip

COPY Gemfile /tmp
COPY Gemfile.lock /tmp

RUN gem install bundler -v "< 2" \
  && bundle install --gemfile=/tmp/Gemfile \
  && rm /tmp/Gemfile /tmp/Gemfile.lock

COPY container-build.sh /usr/local/bin
ENTRYPOINT ["/usr/local/bin/container-build.sh", "-d", "trusty", "-i"]
