#!/bin/sh
set -e

ARCH="amd64"
DISTS="precise"

# ensure the VM has enough entropy to generate sbuild's archive keys
if ! dpkg -s haveged >/dev/null 2>&1; then 
  sudo apt-get install haveged
fi

# Create LXC containers for building .debs from .dscs
for DIST in $DISTS; do
  if ! schroot -ic ${DIST}-${ARCH} >/dev/null 2>&1; then
    mk-sbuild --arch=${ARCH} --name=${DIST} ${DIST}
  fi
done

if sbuild-update --keygen >/dev/null 2>&1; then
  echo "You should now be able to build binary packages for environments"
  echo "with a command like the following:                              "
  echo
  for DIST in $DISTS; do
    echo "    sbuild -A -d ${DIST}-${ARCH} path/to/sourcepackage.dsc      "
  done
  echo
else
  echo "If this is your first time running sbuildinit (you'll know, as  "
  echo "you'll have been asked to supply your name and email, and you'll"
  echo "have got the 'you MUST restart your session' warning, you must  "
  echo "indeed now restart your session, and run sbuildinit again.      "
fi
